# Generated by Django 4.2.9 on 2024-02-06 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadeddocument',
            old_name='document',
            new_name='file',
        ),
    ]
