# Generated by Django 4.2.9 on 2024-02-08 01:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_document_uploadeddocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='test_field',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
