# Generated by Django 4.2.9 on 2024-02-08 01:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_uploadeddocument_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='test_field',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
