# Generated by Django 4.2.9 on 2024-02-13 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_alter_uploadeddocument_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='test_field',
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='participants',
            field=models.ManyToManyField(related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
