# Generated by Django 4.2.9 on 2024-02-15 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
